
baseURL = "https://arjvn.xyz"


theme = ["hugo-bearblog", "hugo-shortcode-gallery"]

title = "Arjun's Webpage"
author = "Arjun 9124"
copyright = "Copyleft © 2026, Arjun 9124."
languageCode = "en-IN"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

summarylength = 20

timeout = 180000

[permalinks]
  blog = "/blog/:slug/"
  tags = "/tag/:slug"

[params]
  enablePostNavigator = true
  description = "arjun's personal webpage"

  
  # favicon = "images/favicon.png"

  images = ["images/share.png"]


  title = "Hugo ʕ•ᴥ•ʔ Bear"

  # hideMadeWithLine = true

  # dateFormat = "2006-01-02"


[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

